# Messages
MSG_NO_COLLISION = "No collisions detected!"
MSG_TOTAL_COLLISIONS = "Total collisions: {}"
MSG_MATCHES_HEADER = "Birthdays shared among people are"
MSG_MATCH_DETAIL = "  {} occurs {} times"
MSG_GENERATED_BIRTHDAYS = "Here are the birthdays for {} people:"
MSG_WELCOME1 = "=== Birthday Paradox Game ==="
MSG_WELCOME2 = "Try your luck: How many people share the same birthday?\n"
MSG_INPUT = "How many birthdays shall I generate ? (1 - {}): "
MSG_INPUT_ERROR = "Invalid Input. Enter a number between 1 and {}."
MSG_SIMULATION = "Let's run the Simulation for {} people {} time..."
MSG_SIMULATION_ENTER = "Please Enter to Begin..."
MSG_SIMULATION_BREAK="In Progress... {} Simulations run completed"
MSG_SIMULATION_RESULT_HEADER = "=== Simulation Results ==="
MSG_SIMULATION_MATCH = "Out of {simulations} simulations with {group_size} people:"
MSG_SIMULATION_COUNT = "  - There was at least one matching birthday in {count} simulations."
MSG_SIMULATION_PROBABILITY = "  - This means a group of {group_size} people has a {probability}% chance of sharing a birthday."
MSG_SIMULATION_FUN = "  - That's probably more than you would expect!"

